# BasicCAD

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)

## Base

### Description

The first assignment is to create the caster base.  The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges.

### Evidence
[The Base in Onshape](https://cvilleschools.onshape.com/documents/0d70f655203ca304cb3c5b7d/w/f55603f962f6fc74f5548a68/e/41d730c570a8d75fce9f51b6)

### Image

<img src="https://github.com/OneCHSEngr/BasicCAD/blob/master/images/Base.jpg" width="400">

### Reflection

This was my first Onshape part and [following along with Dr. Shields made it super easy.](https://www.youtube.com/watch?v=93BFUD-HAG8&feature=emb_title&scrlybrkr=5670f0b4)  I learned about 
* sketching (shortcut **shift-s**)
* constructions lines (shortcut **Q**)
* dimensions (shortcut **D**)
* extruding both add and remove (shortcut key **E**)
* linear patterns (no shortcut)

Onshape is awesome.  I found it really helpful to rename all my sketches.  It is going to be a GREAT year in engineering.

---


## Mount

### Description

The second assignment is to create a mount for the base. The mounts dimensions are 120mm x 120mm. It has 4 symmetric holes in the corners, 10mm in diameter, 20mm from each side. It has another 25 mm circle in the center of the square.

### Evidence
The mount in onshape.https://cvilleschools.onshape.com/documents/217da60652cf40b47fa05207/w/e5e6ac1275bb1d2e5a18268a/e/bce491aeac698bce4beeec88

### Image

<img src="https://github.com/Gbiller01/BasicCAD/blob/main/Images/Screenshot%202020-10-01%20at%2016.00.53.png?raw=true" width="400">

### Reflection
The mount is not a very difficult piece, it's quite small and simple. The most important thing is to just keep it very symmetrical and just don’t fail. If you've completed the onshape course then you can easily do it.

---


## Fork

### Description
You start with an 80mm diameter circle then extrude it 8mm thick. After that you need to make a sketch on one face of the circle which is a rectangle (long side to the center) that is 40mm by 5mm. The close edge of the rectangle is 15mm away from the center. Now just make a construction line parallel to the long side of the rectangle through the center of the circle. Mirror the rectangle with this line. Extrude the rectangles 75mm and fillet the sides to make it look nice. Once you’ve done this you can make a hole through both sides that has a 10mm diameter and has its center 15 mm from the top. Sadly you're not done and you need to flip it over and start a new sketch on the other side. Starting at the center you need to make 2 concentric circles of 15 and 20mm. Extrude them 60mm. You will need to chamfer the edges of the first circle and the outside edge of the mounting place you just made.

### Evidence
https://cvilleschools.onshape.com/documents/217da60652cf40b47fa05207/w/e5e6ac1275bb1d2e5a18268a/e/f30d23f894690dfeec637142

### Image

### Reflection
Just taking time is what helps most. 

---


## Tire

### Description
I had lots of trouble with this so don't ask me. If you watch the video that's what helped in the end. Also make the tire black, it looks better.

### Evidence
https://cvilleschools.onshape.com/documents/217da60652cf40b47fa05207/w/e5e6ac1275bb1d2e5a18268a/e/691533f8249dc30487ae9893

### Image

### Reflection
The angle part at the beginning is very difficult.

---


## Wheel

### Description
To start off you just make 2 parallel rectangles 
on top and bottom of a thinner rectangle so it looks like this. Perfect drawing. Anyway the dimensions of it look like this.
After that just rotate this all the way around the center. Once you've done that then you need to make spokes so start a sketch on the side of the rim. Make two concentric circles with radiuses of 18 and 30mm. Make two more lines that are at a 60 degree angle from each other. Cut out that 60 degree segment with the extrude feature and then make a circular pattern of it 5 times. Add a 1mm fillet to the inside edges of the rim to make it look nice and you're done.

### Evidence
https://cvilleschools.onshape.com/documents/217da60652cf40b47fa05207/w/e5e6ac1275bb1d2e5a18268a/e/3f7542ed53a6f78a6ff14515

### Image

### Reflection
Easier than i thought it would be.

---


## AxleCollarBearings

### Description
The Axle collar Bearings are just the last few pieces to help the caster work smoothly. Watching the video is the best way to do this one because he shows you the use tool.

### Evidence
https://cvilleschools.onshape.com/documents/217da60652cf40b47fa05207/w/e5e6ac1275bb1d2e5a18268a/e/5b29865b65f2151483f64b84
https://cvilleschools.onshape.com/documents/217da60652cf40b47fa05207/w/e5e6ac1275bb1d2e5a18268a/e/1354aaed4cac479ba80e9211


### Image

### Reflection

---
